from .prompts import (
    CLASSIFICATION_SYSTEM_MESSAGE,
    THEME_RECOGNITION_SYSTEM_MESSAGE,
    TAXONOMY_EXAMPLE,
    THEME_RECOGNITION_JSON_FORMAT,
    METHOD_JSON_FORMAT,
    SENTENCE_ANALYSIS_JSON_EXAMPLE,
    SUMMARY_JSON_STRUCTURE,
    HUMAN_MESSAGE_PROMPT,
)